-- ================================================================
-- MSOT QUEST: GAMIFIED LEARNING PLATFORM - SUPABASE SCHEMA
-- Run this in your Supabase SQL Editor (SQL Editor -> New Query -> Run)
-- ================================================================

-- 1. Profiles / Students Table
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    roll_no TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'student' CHECK (role IN ('student', 'faculty', 'admin')),
    department TEXT DEFAULT 'Computer Science',
    section TEXT DEFAULT 'CSE-A',
    campus TEXT DEFAULT 'Main Campus',
    xp INTEGER DEFAULT 120,
    level INTEGER DEFAULT 2,
    streak_days INTEGER DEFAULT 4,
    streak_freezes_left INTEGER DEFAULT 2,
    is_anonymous BOOLEAN DEFAULT false,
    last_active_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. XP Ledger (Audit trail for every point earned)
CREATE TABLE IF NOT EXISTS xp_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    xp_amount INTEGER NOT NULL,
    reason TEXT NOT NULL,
    verified BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. XP Rules Engine (Admin Configurable)
CREATE TABLE IF NOT EXISTS xp_rules (
    rule_key TEXT PRIMARY KEY,
    action_name TEXT NOT NULL,
    suggested_xp INTEGER NOT NULL,
    daily_limit TEXT NOT NULL,
    updated_by TEXT DEFAULT 'Admin'
);

INSERT INTO xp_rules (rule_key, action_name, suggested_xp, daily_limit) VALUES
('attend_class', 'Attend a Class', 10, 'Per class, official attendance only'),
('submit_homework', 'Submit Homework on Time', 20, 'Per assignment'),
('daily_quiz_base', 'Daily Quiz Base Completion', 15, 'Once per day'),
('daily_quiz_correct', 'Daily Quiz Per Correct Answer', 5, 'Max 5 questions'),
('biweekly_test_mult', 'Bi-weekly Test Score Multiplier (Score % / 2)', 50, 'Per test'),
('coding_easy', 'Solve Easy Coding Problem', 10, 'Max 10 per day'),
('coding_medium', 'Solve Medium Coding Problem', 20, 'Max 10 per day'),
('coding_hard', 'Solve Hard Coding Problem', 40, 'Max 10 per day'),
('club_activity', 'Club Activity Participation', 25, 'Per verified club day'),
('streak_7_bonus', '7-Day Streak Bonus', 50, 'Once per 7 days')
ON CONFLICT (rule_key) DO NOTHING;

-- 4. Quests & Badges
CREATE TABLE IF NOT EXISTS quests (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    xp_reward INTEGER NOT NULL,
    target_count INTEGER NOT NULL,
    description TEXT NOT NULL
);

INSERT INTO quests (id, title, category, xp_reward, target_count, description) VALUES
('quest_recursion', 'Master of Recursion', 'Topic Quest', 60, 5, 'Solve 5 recursion problems in code lab'),
('quest_attendance', 'Perfect Attendance Week', 'Milestone', 50, 5, 'Attend all 5 lecture days without absent'),
('quest_improvement', 'The Comeback Kid', 'Improvement', 80, 1, 'Score +15% higher than previous bi-weekly test'),
('quest_peer_review', 'Helping Hand', 'Community', 40, 2, 'Help review 2 peer study notes')
ON CONFLICT (id) DO NOTHING;

-- 5. Rewards Store Items
CREATE TABLE IF NOT EXISTS store_items (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    cost_xp INTEGER NOT NULL,
    stock INTEGER DEFAULT 50,
    description TEXT NOT NULL
);

INSERT INTO store_items (id, title, category, cost_xp, stock, description) VALUES
('perk_canteen', 'MSOT Canteen Snack Voucher', 'Food & Fun', 250, 30, 'Free coffee + puff voucher at MSOT cafeteria'),
('perk_hoodie', 'MSOT Limited Edition Tech Hoodie', 'Merch', 1200, 10, 'Official fleece hoodie with MSOT Quest patch'),
('perk_mentor', '1-on-1 Alumni Mentor Session', 'Career', 600, 15, '45 min mock interview or resume review with FAANG alumni'),
('perk_pass', 'MSOT Annual Hackathon Fast-Track Pass', 'Event', 400, 25, 'Skip screening round for the annual campus hackathon')
ON CONFLICT (id) DO NOTHING;

-- 6. Anti-Gaming Audit Logs
CREATE TABLE IF NOT EXISTS anti_gaming_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    flag_type TEXT NOT NULL,
    details TEXT NOT NULL,
    severity TEXT CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH')),
    status TEXT DEFAULT 'pending_review',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE xp_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE xp_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE quests ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE anti_gaming_logs ENABLE ROW LEVEL SECURITY;

-- Development / Demo RLS Policies (Allow access with Anon Key)
CREATE POLICY "Public Read Profiles" ON profiles FOR SELECT USING (true);
CREATE POLICY "Public Insert Profiles" ON profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Profiles" ON profiles FOR UPDATE USING (true);

CREATE POLICY "Public Read Ledger" ON xp_ledger FOR SELECT USING (true);
CREATE POLICY "Public Insert Ledger" ON xp_ledger FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Rules" ON xp_rules FOR SELECT USING (true);
CREATE POLICY "Public Update Rules" ON xp_rules FOR UPDATE USING (true);

CREATE POLICY "Public Read Quests" ON quests FOR SELECT USING (true);
CREATE POLICY "Public Read Store" ON store_items FOR SELECT USING (true);
CREATE POLICY "Public Read AntiGaming" ON anti_gaming_logs FOR SELECT USING (true);
